### PR TITLE
Added a new question

### PR DESCRIPTION
**Pull request by davidmroth**
You can see what changes I made by reviewing the diff.  I added another set of questions ( You'll need to update the strings files)

https://www.git-tower.com/learn/git/ebook/en/command-line/advanced-topics/diffs

Let me know what questions you have!

### CODE REVIEW

**Comment by al130m** [comment]
I was able to pull the code and update the strings. I have included the
string for a true/ false question, and still need to write the java file to
give credit for the correct text answer to the last question. The answer is
"Commencal" When I started writing the activity_main.xml file I got an
error in java "Error: cannot find symbol variable radioQuestion_2

**Comment by al130m** [comment]
Alright I figured the java error, and pushed my updates again. I set the
total score to be 40. I just need help with the boolean equation for the
true false, and the answer to the text question

**Comment by davidmroth** [comment]
Send me a screenshot pls. Weird, because it worked in my end. Did you make
changes?

**Comment by davidmroth** [comment]
Never mind, just saw your last comment

**Comment by al130m** [comment]
I seem to to take one step forward. and 2 back. I tried to clean up
activity_main.xml file by removing unneeded code, and using ScrollView,
instead of Linear Layout. The code run fine in the studio however now
crashes on startup on my device

**Comment by al130m** [comment]
Update: I have the code working, and taking score for all but one question.
The text response question. How do I write the MainActivity.java code for
that?

**Comment by davidmroth** [comment]
You should be able to follow the code that you already have. I'll give you
a hint, and see how far you can get....

You'll need to get a reference to the EditText by using the method,
'findById'. Once you have a reference to the EditText widget, you'll need
to call the 'getText()' method. Once you have the String that represents
the text that user typed, you'll simply need to compare that to the answer
you are expecting. If it matches, then increment the points by +10 or
whatever.

(I'm going off of memory, but most of this should be correct)

Let me know if that kinda makes sense.

Also, don't forget...Google is your friend.

Give this a shot, and push your code, so I can review the changes you have
made when you're done.


Best Regards,

**Comment by al130m** [comment]
I just pushed the code that I have so far. Let me know if it works for you.

**Comment by al130m** [comment]
I adopted your code to the app, I am not getting any score for questions 1
or 2 no matter the answer I select, I am getting 33% for the true false

**Comment by davidmroth** [comment]
Lets chat on tomorrow.  I know this works, because I tested it.  Just read
the code and it will tell you how to get the answer right (provided you did
not alter the code).

Here's the explanation:
https://gist.github.com/davidmroth/ee17bdfd2c39b52769985bbc55284ae0

Now here is your homework before we talk on tomorrow... What two questions
do you have to select to get 1 point? Respond via email.


Best Regards,
David Roth

**Comment by al130m** [comment]
It looks like answers 1 and 4, or 2 and 3 will result in right answer, but
I do not get that result. I was able to get question 2 to work correctly by
changing the text in code for

**Comment by al130m** [comment]
I got question 1 working now, by replacing the question1_1 text with the
correct texts from the strings. I then modified the equation for the
correct answer to only be correct when choices 1,2,4 are selected. I still
not sure how to start the java equation to check the text answer response,
and give credit for the correct input

**Comment by davidmroth** [comment]
push your updated code, so I can see the changes.

**Comment by al130m** [comment]
I just pushed it.

**Comment by davidmroth** [comment]
I don't think you did:

image

**Comment by al130m** [comment]
From Android Studio, I am right clicking on SimpleQuiz [Simple Quiz]
folder, clicking on Git, Repository, then push. Android Studio shows push
complete, but nothing happens

**Comment by davidmroth** [comment]
Did you commit your changes?

**Comment by al130m** [comment]
That must be what I was doing wrong. It has been committed

**Comment by davidmroth** [comment]
Still not it. :-(

https://github.com/al130m/SimpleQuiz <---- Look at the "latest commit" date.

[image: image.png]

**Comment by al130m** [comment]
Fingers crossed I got it this time. There is so much to learn other than
Android Studio!!
[image: image.png]

**Comment by al130m** [comment]
Well the time for the degree program is over, and I will have to report to
David Waldo tomorrow. There is a 3 month extension that I can get for about
$500, and complete the course.  I do have a proposal for you! If you can
give me a few in home tutor sessions, help me get up to speed with git hub,
and some of the basics, I will ask for the extension. In exchange, if you
need any home remodel/ maintenance projects that you need help with, we
could do some bartering. Let me know what you think. I have my one on one
with Waldo at 9am.

**Comment by davidmroth** [comment]
Sure, I can do that.  I'll make sure you pass.

**Pull request merged**
